server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: postgres
    password: 1004

  jpa:
    hibernate:
      ddl-auto: update  # Esto permite que Hibernate cree o actualice el esquema automáticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/issuer
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
